### ISSUE TITLE
BUG: 'readable-tailwind/multiline' Value for 'indent' should be integer

### ISSUE THREAD

**Issue by letoast** [schoero/eslint-plugin-readable-tailwind#20]
Doesn't accept 'tab'

![image](https://github.com/schoero/eslint-plugin-readable-tailwind/assets/8151795/6cd3ffa1-6bac-4d26-8c3d-2725f16b8972)

**Comment by schoero** [comment]
A fix is published with v1.3.1 on npm.

Thank you for reporting.
