### ISSUE TITLE
[Bug] readable-tailwind/multiline weird autofix behavior

### ISSUE THREAD

**Issue by ivan-palatov** [schoero/eslint-plugin-readable-tailwind#57]
Hi, I am using this plugin in a project with typescript and react, using legacy eslint config. There is a weird issue with the `readable-tailwind/multiline` rule in one particular situation which is repeated across different components in the project.

## Component sample code:

```tsx
function Foo() {
  return (
    <GroupRow
      folderBottomIcon={
        <WorkTwoToneIcon className="text-primary absolute bottom-1 right-0.5 !h-4 !w-4" />
      }
    />
  );
}
```

## .eslintrc.json

```json
"env": {
    "browser": true
  },
"plugins": [
    "@typescript-eslint",
    "prettier",
    "import",
    "react",
    "react-hooks",
    "readable-tailwind"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/recommended",
    "plugin:import/typescript",
    "prettier",
    "plugin:tailwindcss/recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:readable-tailwind/warning"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest"
  },
  "settings": {
    "import/resolver": {
      "typescript": true,
      "node": true
    },
    "react": {
      "componentWrapperFunctions": ["observer"],
      "formComponents": ["FormDialog", "Form"],
      "linkComponents": [
        {
          "linkAttribute": "to",
          "name": "Link"
        }
      ],
      "version": "detect"
    }
  },
```

## The problem

The auto fix first suggests the following change with the message `Incorrect line wrapping: "text-primary absolute bottom-1 right-0.5 !h-4 !w-4"`:

```tsx
function Foo() {
  return (
    <GroupRow
      folderBottomIcon={
        <WorkTwoToneIcon
          className={`
          text-primary absolute bottom-1 right-0.5 !h-4 !w-4
        `}
      }
    />
  );
}
```

But then it suggests reverting it back to the first code snippet with the message : `Unnecessary line wrapping: "\n text-primary absolute bottom-1 right-0.5 !h-4 !w-4\n "`

Also, I do believe this is the reason for heap out of memory crit when running eslint on this project:
![image](https://github.com/user-attachments/assets/4c4d121b-9e42-466e-aaf1-70f3227305c0)

## Final comments

Also, I believe I should mention that the project in question is a part of nx monorepo with 12 other projects, all of which run and apply autofix no problem. I think there is an issue with the exact number for line wrapping not being handled correctly, although the number of symbols for the string in question is 90 with left spaces and 82 without.

**Comment by schoero** [comment]
Hi, thank you for the detailed error report. I am currently on vacation. I will be able to look into it in 3 weeks.

**Comment by schoero** [comment]
I tried to look into this today, but I'm having trouble to reproduce the error. Are you using the latest version of the plugin? I remember having this issue in older versions.

Can you post the output of `npm ls eslint-plugin-readable-tailwind`

**Comment by ivan-palatov** [comment]
@schoero sorry for the long wait, was working on a complex feature.

I am definitely using the latest version of the plugin. I could create a reproduction repo later in the week.

![image](https://github.com/user-attachments/assets/0c0d3942-01ba-4bca-88f6-5387682bb35b)

**Comment by schoero** [comment]
I published a new version. It does not fix the issue, but it provides better warnings and displays the before and after of the tailwind class string.

Maybe this can give us enough insights before you try to create a reproduction.

**Comment by schoero** [comment]
I ran into [a similar issue](https://github.com/schoero/eslint-plugin-readable-tailwind/pull/61) today and published a fix for it in v1.8.2.

If this issue still persists after upgrading to v1.8.2, feel free to reopen.

**Comment by VityaSchel** [comment]
This is still happening as of 3.7.5
One of the component that causes this problem for me:
```svelte
<span class="absolute top-6 right-6 z-1 rounded-md bg-black/50 px-1.5 text-white">foobar</span>
```

1st lint warning:
```
Incorrect line wrapping. Expected

"absolute·top-6·right-6·z-1·rounded-md·bg-black/50·px-1.5·text-white"

to be

"↵
→absolute·top-6·right-6·z-1·rounded-md·bg-black/50·px-1.5·text-white↵
"eslint[better-tailwindcss/enforce-consistent-line-wrapping](https://github.com/schoero/eslint-plugin-better-tailwindcss/blob/main/docs/rules/multiline.md)
```

2nd lint warning:
```
Unnecessary line wrapping. Expected

"↵
→absolute·top-6·right-6·z-1·rounded-md·bg-black/50·px-1.5·text-white↵
"

to be

"absolute·top-6·right-6·z-1·rounded-md·bg-black/50·px-1.5·text-white"eslint[better-tailwindcss/enforce-consistent-line-wrapping](https://github.com/schoero/eslint-plugin-better-tailwindcss/blob/main/docs/rules/multiline.md)
```
my eslint.config.js:
```js
import prettier from 'eslint-config-prettier';
import js from '@eslint/js';
import { includeIgnoreFile } from '@eslint/compat';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import { fileURLToPath } from 'node:url';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';
import eslintPluginBetterTailwindcss from 'eslint-plugin-better-tailwindcss';

const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url));

export default ts.config(
	includeIgnoreFile(gitignorePath),
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		settings: {
			'better-tailwindcss': {
				entryPoint: 'src/app.css'
			}
		},
		plugins: {
			'better-tailwindcss': eslintPluginBetterTailwindcss
		},
		rules: {
			...eslintPluginBetterTailwindcss.configs['recommended-warn'].rules,
			'better-tailwindcss/no-unregistered-classes': 'off',
			'better-tailwindcss/enforce-consistent-line-wrapping': [
				'error',
				{
					indent: 'tab'
				}
			]
		}
	}
);
```
Dependencies versions:
```
"eslint": "^9.18.0",
"eslint-config-prettier": "^10.0.1",
"eslint-plugin-better-tailwindcss": "^3.7.5",
"prettier-plugin-tailwindcss": "^0.6.11",
```
.prettierrc:
```json
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"htmlWhitespaceSensitivity": "ignore",
	"printWidth": 100,
	"plugins": [
		"prettier-plugin-svelte",
		"prettier-plugin-tailwindcss"
	],
	"overrides": [
		{
			"files": "*.svelte",
			"options": {
				"parser": "svelte"
			}
		}
	],
	"tailwindStylesheet": "./src/app.css"
}
```

**Comment by VityaSchel** [comment]
One way I found to fix it is to set printWidth to 80 in eslint config under better-tailwindcss settings object and to the same value in prettier config. Still would love to hear from @schoero about this issue!

**Comment by schoero** [comment]
I can reproduce it. The root cause seems to be that prettier is less strict with its line wrapping. 

Consider this example:

1. ESLint reports because the classes overflow the `printWidth` (indicated with the vertical ruler). Prettier doesn't report here because it is [less strict](https://prettier.io/docs/options.html#print-width).

> Prettier’s printWidth option does not work the same way. It is not the hard upper allowed line length limit. It is a way to say to Prettier roughly how long you’d like lines to be. Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.

<img width="710" height="60" alt="Image" src="https://github.com/user-attachments/assets/302ed1c9-daae-4722-98a6-d18a83e50b64" />

<br />
<br />

2. ESLint wants to fix it to the following, but now prettier reports because it wants to wrap the `className` attribute to a new line.

<img width="710" height="100" alt="Image" src="https://github.com/user-attachments/assets/5b1e946d-f229-4418-bcbf-8f0d6cce41cb" />

<br />
<br />

3. If the attribute gets wrapped onto a new line, this now causes the class string to have sufficient space and therefore eslint will collapse it.

<img width="710" height="135" alt="Image" src="https://github.com/user-attachments/assets/d2da644e-0e3d-4eed-aaba-fc75186bf60d" />

<br />
<br />

4. Collapsing the classes to a single line now causes prettier to want to move the className attribute back to the original line and the whole chain repeats.

<img width="710" height="105" alt="Image" src="https://github.com/user-attachments/assets/821d8b07-5100-4b33-a73f-cd213cf9581e" />

For the plugin to handle it, it would need to adopt Prettier’s flexible line-wrapping logic, but since the plugin is independent of Prettier, that isn’t practical.

I would recomment to just use `// prettier-ignore` or `// eslint-disable-next-line` for these specific cases.
