### ISSUE TITLE
Usage with eslint 9 / flat config

### ISSUE THREAD

**Issue by arcs-** [schoero/eslint-plugin-readable-tailwind#58]
In our project we've upgraded to eslint 9 and the new flat config, it seems this plugin does not work yet in that configuration. Is this correct or is there a way I haven't figured out?

**Comment by schoero** [comment]
It should definitely be compatible with ESLint 9 and the flat config format. You should find a working config in the [parsers section](https://github.com/schoero/eslint-plugin-readable-tailwind?tab=readme-ov-file#parsers) for the specific flavor you are using.

Do you experience any errors? If so, can you post the error message and the part of the config for eslint-plugin-readable-tailwind?

**Comment by arcs-** [comment]
It was my error, I didn't understand the flat config correctly. Thanks for the great plugin!
